### ISSUE TITLE
Create scrapers for data without an API

### ISSUE THREAD

**Issue by luciencd** [SpencerNorris/SuperPACs#20]
Some data is unavailable through our APIs, and we need to be able to get it anyways.

Like:
The mission statement of SuperPACs.
etc...

We must create scrapers that work alongside our api endpoints to populate our data.

**Comment by SaswatB** [comment]
Spencer finished this correct?

**Comment by SpencerNorris** [comment]
Sort of. It appears as if all of the bill data was successfully scraped, need to pull down the vote data next. The scrapers and instructions are in this repo: https://github.com/unitedstates/congress .

**Comment by SaswatB** [comment]
We found apis for this data
