### ISSUE TITLE
Investigate caching of API data

### ISSUE THREAD

**Issue by luciencd** [SpencerNorris/SuperPACs#21]
We need to cache our API requests, so that we don't run out of requests. 
Also increases performance.

**Comment by luciencd** [comment]
Pickled the data in the feature/datasource branch.

**Comment by luciencd** [comment]
Will soon make it so that the pickled data file gets removed every day, and add a "force" flag argument to the seeder.py file that forces the api's to update.

**Comment by SaswatB** [comment]
Done
